name = "Pipette"
uuid = "0a8c84c6-482d-4399-887f-69614b2ff022"
authors = ["Martin <martin@umlet.com>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
REPL="<0.0.1, 1"
julia = "1.9.0"
